{
  voornaam: 'Dimitri',
  naam: 'Van Hoecke',
  gebruikersnaam: 'dimitri.vanhoecke',
  internnummer: null,
  status: 'actief',
  extravoornamen: null,
  initialen: null,
  roepnaam: null,
  geslacht: 'm',
  geboortedatum: 1977-10-28T00:00:00.000Z,
  geboorteplaats: 'Gent',
  geboorteland: 'België',
  rijksregisternummer: null,
  straat: 'Gensteaardeweg ',
  huisnummer: '2',
  busnummer: 'B',
  postcode: '9032',
  woonplaats: 'Wondelgem',
  land: 'België',
  emailadres: 'dimitri.vanhoecke@edugo.be',
  website: null,
  mobielnummer: '+32473218899',
  telefoonnummer: '+32473218899',
  fax: null,
  instantmessenger: null,
  sorteerveld: 'vanhoecke-dimitri',
  stamboeknummer: 'NULL',
  koppelingsveldschoolagenda: null,
  basisrol: '30',
  klasnummer: null,
  referenceIdentifier: '4203_3_0',
  scannableCode: 'd5c8521c-09ed-5a8e-9f2a-f8ad551d843d',
  isEmailVerified: true,
  isAuthenticatorAppEnabled: true,
  isYubikeyEnabled: false,
  groups: [
    {
      id: '2',
      code: 'Beheerders',
      name: 'Beheerders',
      desc: 'Beheerders',
      isKlas: false,
      isOfficial: false
    },
    {
      id: '3',
      code: 'lkn',
      name: 'Leerkrachten',
      desc: 'Groep leerkrachten',
      isKlas: false,
      isOfficial: false
    },
    {
      id: '5',
      code: 'Directie',
      name: 'Directie',
      desc: 'Directie',
      isKlas: false,
      isOfficial: false
    },
    {
      id: '1181',
      code: '',
      name: 'Keuzegedeelte 1A',
      desc: 'Tijdelijke groep voor enquête 1A',
      isKlas: false,
      isOfficial: false
    }
  ],
  Groep: null,
  internId: null,
  'Belangrijke informatie:': null,
  smartschoolClientUserId: null,
  Middagpauze: null,
  TEST: null,
  godsdienstkeuze: 'Katholieke godsdienst',
  nationaliteitscode: '150',
  nationaliteit: 'Belgische',
  soortleerling: 'Vrije leerling',
  function: null,
  teachercardnumber: null,
  voornaam_coaccount1: null,
  naam_coaccount1: null,
  email_coaccount1: null,
  email_coaccount1_isVerified: false,
  telefoonnummer_coaccount1: null,
  mobielnummer_coaccount1: null,
  type_coaccount1: 0,
  authenticator_app_enabled1: false,
  yubikey_enabled1: false,
  status1: 'niet actief',
  voornaam_coaccount2: null,
  naam_coaccount2: null,
  email_coaccount2: null,
  email_coaccount2_isVerified: false,
  telefoonnummer_coaccount2: null,
  mobielnummer_coaccount2: null,
  type_coaccount2: 0,
  authenticator_app_enabled2: false,
  yubikey_enabled2: false,
  status2: 'niet actief',
  voornaam_coaccount3: null,
  naam_coaccount3: null,
  email_coaccount3: null,
  email_coaccount3_isVerified: false,
  telefoonnummer_coaccount3: null,
  mobielnummer_coaccount3: null,
  type_coaccount3: 0,
  authenticator_app_enabled3: false,
  yubikey_enabled3: false,
  status3: 'niet actief',
  voornaam_coaccount4: null,
  naam_coaccount4: null,
  email_coaccount4: null,
  email_coaccount4_isVerified: false,
  telefoonnummer_coaccount4: null,
  mobielnummer_coaccount4: null,
  type_coaccount4: 0,
  authenticator_app_enabled4: false,
  yubikey_enabled4: false,
  status4: 'niet actief',
  voornaam_coaccount5: null,
  naam_coaccount5: null,
  email_coaccount5: null,
  email_coaccount5_isVerified: false,
  telefoonnummer_coaccount5: null,
  mobielnummer_coaccount5: null,
  type_coaccount5: 0,
  authenticator_app_enabled5: false,
  yubikey_enabled5: false,
  status5: 'niet actief',
  voornaam_coaccount6: null,
  naam_coaccount6: null,
  email_coaccount6: null,
  email_coaccount6_isVerified: false,
  telefoonnummer_coaccount6: null,
  mobielnummer_coaccount6: null,
  type_coaccount6: 0,
  authenticator_app_enabled6: false,
  yubikey_enabled6: false,
  status6: 'niet actief',
  last_successful_login: '2022-11-16 11:57:45',
  last_successful_login_coaccount1: null,
  last_successful_login_coaccount2: null,
  schoolverlater: 0
}